language: python
dist: xenial
python:
  - "2.7"
  - "3.6"
  - "3.7"
before_install:
  - pip install coveralls
install: pip install tox-travis
script: tox
after_success:
  - coveralls
notifications:
  email:
    on_failure: change
    on_success: change
